backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img/uploads"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend:
  # when using a custom proxy server port
  url: http://localhost:8081/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  # allowed_hosts: ['192.168.0.1']
# publish_mode: editorial_workflow
collections:
  - label: "Work"
    name: "work"
    folder: "src/works"
    create: true
    editor:
      preview: false
    sortable_fields: ["weight", "title"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Name 1", name: "name1", widget: "text", required: false }
      - { label: "Name 2", name: "name2", widget: "text", required: false }
      - { label: "Spec", name: "spec", widget: "markdown", required: false }
      - {
          label: "Weight",
          name: "weight",
          widget: "number",
          default: 1,
          required: true,
        }
      - { label: "Cover", name: "cover", widget: "image" }
      - {
          label: "Description",
          name: "description",
          widget: "markdown",
          required: false,
        }
      - {
          label: "Gallery",
          name: "galleryImages",
          widget: "list",
          collapsed: false,
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
        }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.json"
        fields:
          - { label: Meta_Title, name: meta_title, widget: string }
          - { label: Meta_Description, name: meta_description, widget: string }
